<div data-bind="scope: 'random'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app": {
                "components": {
                    "random": {
                        "component": "Training_JsBlock/js/review",
                        "config": {
                            "template": "Training_JsBlock/review",
                            "url": <?= json_encode($block->getUrl('jsblock/review/index')) ?>
                        }
                    }
                }
            }
        }
    }
</script>